ALTER TABLE appointments_tbl
ADD COLUMN IF NOT EXISTS appt_end_time TIME DEFAULT NULL,
ADD COLUMN IF NOT EXISTS estimated_duration_minutes INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS reservation_reference VARCHAR(120) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS reservation_fee DECIMAL(10,2) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS payment_proof_path VARCHAR(500) DEFAULT NULL;
