ALTER TABLE customer_tbl
ADD COLUMN IF NOT EXISTS email_verification_token VARCHAR(64) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS email_verified_at DATETIME DEFAULT NULL,
ADD COLUMN IF NOT EXISTS password_reset_token VARCHAR(64) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS password_reset_expires_at DATETIME DEFAULT NULL;
